export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as Contact } from "./contact/Contact";
export { default as Register } from "./register/Register";
export { default as Login } from "./login/Login";
export { default as Loggedin } from "./logged-in/Loggedin";
export { default as Dashboard } from "./dashboard/Dashboard";
export { default as SuccessRegister } from "./success-register/SuccessRegister";
export { default as ResetPassword } from "./reset-password/ResetPassword";
